#!/bin/sh
# Exit on any error
set -e


echo "Checking if Husky hooks are installed precommit..."
dotnet husky install

echo "Running pre-commit hook for multiple solutions..."

# Find all solution files recursively
solutions=$(find . -name "*.sln")

# Loop through each solution file and run checks
for solution in $solutions
do
  echo "Processing solution: $solution"

  # Run CSharpier to format the code
  dotnet csharpier .

  # Run dotnet format
#   dotnet format $solution --verbosity diagnostic

#   # Build the solution
#   dotnet build $solution

#   # Run tests for the solution
#   dotnet test $solution
done

echo "Pre-commit hook completed successfully."